# Topics
camera_topic: "/gmsl/A0/image_color"
camera_info: "/gmsl/A0/camera_info"
lidar_topic: "/VLP16/front/points"

# Dynamic rqt_reconfigure default bounds
feature_extraction:
  x_min: -10.0
  x_max: 10.0
  y_min: -8.0
  y_max: 8.0
  z_min: -5.0
  z_max: 5.0
  
# Properties of chessboard calibration target
chessboard:
  pattern_size:
    height: 8
    width: 6  
  square_length: 95
  board_dimension:
    width: 590
    height: 900
  translation_error:
    x: 0
    y: 0